// Generated by Wrangler by running `wrangler types`

interface Env {
	JWT_KEY_KV_STORE: KVNamespace;
	IS_DEV: true;
	ENVIRONMENT: "dev";
	WHITELIST_DOMAINS: ["https://useslime.com/","http://localhost"];
	REFRESH_TOKEN_EXPIRES_IN_SECONDS: 15552000;
	ACCESS_TOKEN_EXPIRES_IN_SECONDS: 10800;
	REFRESH_TOKEN_JTI_TIME_SLEW_SECONDS: 30;
	REFRESH_TOKEN_ISSUE_AFTER_SECONDS: 900;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	USER_DURABLE: DurableObjectNamespace<import("./src/index").UserDurableObject>;
	USER_AUTH: D1Database;
}
declare module "*.sql" {
	const value: string;
	export default value;
}