// Generated by Wrangler by running `wrangler types`

interface Env {
	JWT_KEY_KV_STORE: KVNamespace;
	STORE_DURABLE: DurableObjectNamespace<import("./src/index").StoreDurableObject>;
	SLIME_DB: D1Database;
}
declare module "*.sql" {
	const value: string;
	export default value;
}